### ISSUE TITLE
libtile2.0.1.a not found

### ISSUE THREAD

**Issue by shuaibixi** [GreenWaves-Technologies/autotiler#5]
When I get the Autotiler by:
$ cd ~/gap_sdk/
$ make autotiler
It seems libtile2.0.1.a not found.
I have attempted to use vpn but got same error.
![Screenshot from 2019-05-23 16-05-11](https://user-images.githubusercontent.com/25522517/58236316-3c6e0680-7d75-11e9-8c4d-0768934e2e55.png)

**Comment by Yaooooo** [comment]
Hi,
This is because during the installation, there is a small survey. 
In the last question, you need to put the url you would have received from your email registered.
Here, the problem is the url is empty, so it cannot found the server.

Solution:
1, Edit the file "gap_sdk/tools/autotiler/.tiler_url", and put the url address we have sent you in your mail.
2, Remove this file, and restart.

Best,
Yao
